name: Metrics
on:
  schedule: [{cron: "0 * * *https://github.com/ManualMap/ManualMap *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_followup: yes
          plugin_followup_sections: repositories, user #
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage, lines
          plugin_languages_sections: most-used
          plugin_languages_recent_load: 1000
          commits_authoring: manualmap@users.noreply.github.com
